# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\tohan\MyGameEngineIDE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\tohan\MyGameEngineIDE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\tohan\MyGameEngineIDE\CMakeFiles C:\Users\tohan\MyGameEngineIDE\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\tohan\MyGameEngineIDE\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named MyGameEngineIDE

# Build rule for target.
MyGameEngineIDE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MyGameEngineIDE
.PHONY : MyGameEngineIDE

# fast build rule for target.
MyGameEngineIDE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/build
.PHONY : MyGameEngineIDE/fast

external/imgui-sfml/imgui-SFML.obj: external/imgui-sfml/imgui-SFML.cpp.obj
.PHONY : external/imgui-sfml/imgui-SFML.obj

# target to build an object file
external/imgui-sfml/imgui-SFML.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui-sfml/imgui-SFML.cpp.obj
.PHONY : external/imgui-sfml/imgui-SFML.cpp.obj

external/imgui-sfml/imgui-SFML.i: external/imgui-sfml/imgui-SFML.cpp.i
.PHONY : external/imgui-sfml/imgui-SFML.i

# target to preprocess a source file
external/imgui-sfml/imgui-SFML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui-sfml/imgui-SFML.cpp.i
.PHONY : external/imgui-sfml/imgui-SFML.cpp.i

external/imgui-sfml/imgui-SFML.s: external/imgui-sfml/imgui-SFML.cpp.s
.PHONY : external/imgui-sfml/imgui-SFML.s

# target to generate assembly for a file
external/imgui-sfml/imgui-SFML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui-sfml/imgui-SFML.cpp.s
.PHONY : external/imgui-sfml/imgui-SFML.cpp.s

external/imgui/imgui.obj: external/imgui/imgui.cpp.obj
.PHONY : external/imgui/imgui.obj

# target to build an object file
external/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui.cpp.obj
.PHONY : external/imgui/imgui.cpp.obj

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.obj: external/imgui/imgui_demo.cpp.obj
.PHONY : external/imgui/imgui_demo.obj

# target to build an object file
external/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_demo.cpp.obj
.PHONY : external/imgui/imgui_demo.cpp.obj

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.obj: external/imgui/imgui_draw.cpp.obj
.PHONY : external/imgui/imgui_draw.obj

# target to build an object file
external/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_draw.cpp.obj
.PHONY : external/imgui/imgui_draw.cpp.obj

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.obj: external/imgui/imgui_tables.cpp.obj
.PHONY : external/imgui/imgui_tables.obj

# target to build an object file
external/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_tables.cpp.obj
.PHONY : external/imgui/imgui_tables.cpp.obj

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.obj: external/imgui/imgui_widgets.cpp.obj
.PHONY : external/imgui/imgui_widgets.obj

# target to build an object file
external/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_widgets.cpp.obj
.PHONY : external/imgui/imgui_widgets.cpp.obj

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

src/Entity.obj: src/Entity.cpp.obj
.PHONY : src/Entity.obj

# target to build an object file
src/Entity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Entity.cpp.obj
.PHONY : src/Entity.cpp.obj

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/EntityManager.obj: src/EntityManager.cpp.obj
.PHONY : src/EntityManager.obj

# target to build an object file
src/EntityManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/EntityManager.cpp.obj
.PHONY : src/EntityManager.cpp.obj

src/EntityManager.i: src/EntityManager.cpp.i
.PHONY : src/EntityManager.i

# target to preprocess a source file
src/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/EntityManager.cpp.i
.PHONY : src/EntityManager.cpp.i

src/EntityManager.s: src/EntityManager.cpp.s
.PHONY : src/EntityManager.s

# target to generate assembly for a file
src/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/EntityManager.cpp.s
.PHONY : src/EntityManager.cpp.s

src/InputManager.obj: src/InputManager.cpp.obj
.PHONY : src/InputManager.obj

# target to build an object file
src/InputManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/InputManager.cpp.obj
.PHONY : src/InputManager.cpp.obj

src/InputManager.i: src/InputManager.cpp.i
.PHONY : src/InputManager.i

# target to preprocess a source file
src/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/InputManager.cpp.i
.PHONY : src/InputManager.cpp.i

src/InputManager.s: src/InputManager.cpp.s
.PHONY : src/InputManager.s

# target to generate assembly for a file
src/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/InputManager.cpp.s
.PHONY : src/InputManager.cpp.s

src/Physics.obj: src/Physics.cpp.obj
.PHONY : src/Physics.obj

# target to build an object file
src/Physics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Physics.cpp.obj
.PHONY : src/Physics.cpp.obj

src/Physics.i: src/Physics.cpp.i
.PHONY : src/Physics.i

# target to preprocess a source file
src/Physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Physics.cpp.i
.PHONY : src/Physics.cpp.i

src/Physics.s: src/Physics.cpp.s
.PHONY : src/Physics.s

# target to generate assembly for a file
src/Physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Physics.cpp.s
.PHONY : src/Physics.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj
.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/WindowManager.obj: src/WindowManager.cpp.obj
.PHONY : src/WindowManager.obj

# target to build an object file
src/WindowManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/WindowManager.cpp.obj
.PHONY : src/WindowManager.cpp.obj

src/WindowManager.i: src/WindowManager.cpp.i
.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s
.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyGameEngineIDE.dir\build.make CMakeFiles/MyGameEngineIDE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ImGui
	@echo ... MyGameEngineIDE
	@echo ... external/imgui-sfml/imgui-SFML.obj
	@echo ... external/imgui-sfml/imgui-SFML.i
	@echo ... external/imgui-sfml/imgui-SFML.s
	@echo ... external/imgui/imgui.obj
	@echo ... external/imgui/imgui.i
	@echo ... external/imgui/imgui.s
	@echo ... external/imgui/imgui_demo.obj
	@echo ... external/imgui/imgui_demo.i
	@echo ... external/imgui/imgui_demo.s
	@echo ... external/imgui/imgui_draw.obj
	@echo ... external/imgui/imgui_draw.i
	@echo ... external/imgui/imgui_draw.s
	@echo ... external/imgui/imgui_tables.obj
	@echo ... external/imgui/imgui_tables.i
	@echo ... external/imgui/imgui_tables.s
	@echo ... external/imgui/imgui_widgets.obj
	@echo ... external/imgui/imgui_widgets.i
	@echo ... external/imgui/imgui_widgets.s
	@echo ... src/Entity.obj
	@echo ... src/Entity.i
	@echo ... src/Entity.s
	@echo ... src/EntityManager.obj
	@echo ... src/EntityManager.i
	@echo ... src/EntityManager.s
	@echo ... src/InputManager.obj
	@echo ... src/InputManager.i
	@echo ... src/InputManager.s
	@echo ... src/Physics.obj
	@echo ... src/Physics.i
	@echo ... src/Physics.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/WindowManager.obj
	@echo ... src/WindowManager.i
	@echo ... src/WindowManager.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

